# The host on which the exporter should listen to (defaults to 127.0.0.1)
exporter_host: $(PGBOUNCER_EXPORTER_HOST)

# The port on which the exporter should listen to (defaults to 9127)
exporter_port: $(PGBOUNCER_EXPORTER_PORT)

# The list of pgbouncer instances to monitor
pgbouncers:
  - user: $(PGBOUNCER_USER)
    password: $(PGBOUNCER_PASS)
    host: $(PGBOUNCER_HOST)
    port: $(PGBOUNCER_PORT)
    dbname: pgbouncer

    # The pgbouncer connection timeout in seconds (defaults to 5 seconds)
    connect_timeout: 5
